# <center> Numpy Basics </center>

In [1]:
#import numpy module with alias np
import numpy as np


We can create a NumPy ndarray object by using the array() function.
To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:


In [2]:
# Define a numpy array passing a list with  1,2 and 3 as elements in it

import numpy as np

# Creating ndarray from a list
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating ndarray from a tuple
arr2 = np.array((10, 20, 30))


[1 2 3 4 5]


In [3]:
# print output
print(arr2)


[10 20 30]


## Dimensions in Arrays

Create arrays of different dimentions.

a=A numpy array with one single integer 10

b=A numpy array passing a list having a list= [1,2,3]

c=A numpy array passing nested list having [[1, 2, 3], [4, 5, 6]] as elements

d=A numpy array passing nested list having [[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]] as elements

In [4]:
import numpy as np

# a: 0-D array (scalar)
a = np.array(10)

# b: 1-D array
b = np.array([1, 2, 3])

# c: 2-D array
c = np.array([[1, 2, 3], [4, 5, 6]])

# d: 3-D array
d = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]])

# Printing arrays
print("a =", a)
print("b =", b)
print("c =\n", c)
print("d =\n", d)

# Checking dimensions
print("Dimension of a:", a.ndim)
print("Dimension of b:", b.ndim)
print("Dimension of c:", c.ndim)
print("Dimension of d:", d.ndim)

a = 10
b = [1 2 3]
c =
 [[1 2 3]
 [4 5 6]]
d =
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Dimension of a: 0
Dimension of b: 1
Dimension of c: 2
Dimension of d: 3


Are you ready to check its dimention? Use ndim attribute on each variable to check its dimention

In [5]:
#print dimentions of a,b, c and d


import numpy as np

a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)  # Output: 0
print(b.ndim)  # Output: 1
print(c.ndim)  # Output: 2
print(d.ndim)  # Output: 3


0
1
2
3


Hey hey. Did you see! you have created 0-D,1-DeprecationWarning, 2-D and 3-D arrays.

Lets print there shape as well. You can check shape using shape attribute



In [6]:
# print shape of each a,b ,c and d


import numpy as np

a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]])

print(a.shape)  # ()
print(b.shape)  # (3,)
print(c.shape)  # (2, 3)
print(d.shape)  # (2, 2, 3)



()
(3,)
(2, 3)
(2, 2, 3)


Lets check data type passed in our array. To check data type you can use dtype attribute

In [7]:
# print data type of c and d

import numpy as np

a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]])

print(a.dtype)
print(b.dtype)
print(c.dtype)
print(d.dtype)



int64
int64
int64
int64


Above output mean our array is having int type elements in it.

Lets check the type of our variable. To check type of any numpy variable use type() function 

In [8]:
#print type of a and b variable


import numpy as np

a = np.array(10)
b = np.array([1, 2, 3])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], 
              [[1, 2, 3], [4, 5, 6]]])

print(type(a))
print(type(b))
print(type(c))
print(type(d))



<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [9]:
import numpy as np

b = np.array([1, 2, 3])

print(len(b))  # Output: 3

3


Bravo!You have Defined ndarray i.e numpy array in variable a nd b. Also you have successfully learned how to create numpy. 

Create two list l1 and l2 where, l1=[10,20,30] and l2=[40,50,60]
Also define two numpy arrays l3,l4 where l3 has l1 as element and l4 has l2 as element


In [10]:
import numpy as np

# Creating lists
l1 = [10, 20, 30]
l2 = [40, 50, 60]

# Creating NumPy arrays using the lists
l3 = np.array(l1)
l4 = np.array(l2)

# Printing results
print("l1:", l1)
print("l2:", l2)
print("l3:", l3)
print("l4:", l4)

l1: [10, 20, 30]
l2: [40, 50, 60]
l3: [10 20 30]
l4: [40 50 60]


Lets multiply each elements of l1 with corresponding elements of l2

Here use list comprehention to do so. Lets see how much you remember your work in other assignments.

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line<br>
eg. %timeit my_code

In [11]:
l1 = [10, 20, 30]
l2 = [40, 50, 60]

%timeit result = [x * y for x, y in zip(l1, l2)]

363 ns ± 40.6 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Lets mulptiply l3 and l4

Note: use %timeit as prefix before your line of code inorder to calculate total time taken to run that line

In [12]:

import numpy as np

l3 = np.array([10, 20, 30])
l4 = np.array([40, 50, 60])

%timeit result = l3 * l4


475 ns ± 57.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


Don't worry if still your one line of code is running. Its because your system is calculating total time taken to run your code.

Did you notice buddy! time taken to multiply two lists takes more time than multiplyimg two numpy array.
Hence proved that numpy arrays are faster than lists.

**Fun Fact time!:**

You know in many data science interviews it is asked that what is the difference between list and array.<br>


In [13]:
import numpy as np

arr = np.arange(1, 11)

print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


This means using arrange we get evenly spaced values within a given interval. Interval? Yes you can mention interval as well as third parameter in it.

In [14]:
import numpy as np

arr = np.arange(1, 11, 2)

print(arr)

[1 3 5 7 9]


In [15]:
import numpy as np

arr = np.eye(3)

print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
import numpy as np

x = np.arange(1, 17)

print(x)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [17]:
x = x.reshape(2, 8)

print(x)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


As you can see above that our x changed into 2D matrix

2. Reshaping 1-D to 3-D array


In [18]:
x_3d = x.reshape(2, 2, 4)

print(x_3d)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]]


In [19]:
x_2d = x.reshape(4, -1)

print(x_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [20]:
y = x.reshape(2, 4, -1)

print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]
  [13 14]
  [15 16]]]


In [21]:
z = y.flatten()

print(z)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [22]:
import numpy as np

a = np.arange(2, 18, 2)

print(a)

[ 2  4  6  8 10 12 14 16]


In [23]:
print(a[2])

6


In [24]:
print(a[2], a[4], a[6])

6 10 14


Lets check the same for 2 D array

In [25]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
print(a[2][2])

9


Well done!

Now lets check indexing for 3 D array 

In [27]:
import numpy as np

b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [28]:
b = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

In [29]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[0:5])

[1 2 3 4 5]


Note: The result includes the start index, but excludes the end index.



In [31]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[5:])

[6 7]


In [32]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[:5])

[1 2 3 4 5]


**STEP**

Use the step value to determine the step of the slicing:

In [33]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[1:7:2])

[2 4 6]


Did you see? using step you were able to get alternate elements within specified index numbers.

In [34]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

print(arr[1:7:2])

[2 4 6]


well done!

Lets do some slicing on 2-D array also. We already have 'a' as our 2-D array. We will use it here.

**Array slicing in 2-D array.**

In [35]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [36]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

In [37]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[:, 2])

[3 6 9]


In [38]:
import numpy as np

a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[:, 1:])

[[2 3]
 [5 6]
 [8 9]]


Hurray! You have learned Slicing in Numpy array. Now you know to access any numpy array.

## Numpy copy vs view

In [39]:
x1 = a[:, 1:]

print(x1)

[[2 3]
 [5 6]
 [8 9]]


In [40]:
x2 = x1

print(x2)

[[2 3]
 [5 6]
 [8 9]]


In [41]:
print(x1)
print(x2)

[[2 3]
 [5 6]
 [8 9]]
[[2 3]
 [5 6]
 [8 9]]


Ok now you have seen that both of them are same 

In [42]:
x2[0, 0] = 10

print(x2)

[[10  3]
 [ 5  6]
 [ 8  9]]


In [43]:
print(x1)
print(x2)

[[10  3]
 [ 5  6]
 [ 8  9]]
[[10  3]
 [ 5  6]
 [ 8  9]]


In [44]:
import numpy as np

print(np.shares_memory(x1, x2))

True


Hey It's True they both share memory

Shall we try **view()** function also likwise.

In [45]:
x3 = x1.view()

print(x3)

[[10  3]
 [ 5  6]
 [ 8  9]]


In [46]:
import numpy as np

print(np.shares_memory(x1, x3))

True


Woh! simple assignment is similar to view. That means 
The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

Don't agree? ok lets change x3 and see if original array i.e. x1 also changes

In [47]:
x3[0, 0] = 100

print(x3)

[[100   3]
 [  5   6]
 [  8   9]]


In [48]:
print(x1)
print(x3)

[[100   3]
 [  5   6]
 [  8   9]]
[[100   3]
 [  5   6]
 [  8   9]]


Now its proved.

Lets see how **Copy()** function works

In [49]:
x4 = x1.copy()

print(x4)

[[100   3]
 [  5   6]
 [  8   9]]


In [50]:
x4[-1, -1] = 900

print(x4)

[[100   3]
 [  5   6]
 [  8 900]]


In [51]:
print(x1)
print(x4)

[[100   3]
 [  5   6]
 [  8   9]]
[[100   3]
 [  5   6]
 [  8 900]]


Hey! such an intresting output. You noticed buddy! your original array didn't get changed on change of its copy ie. x4.

Still not convinced? Ok lets see if they both share memory or not

In [52]:
import numpy as np

print(np.shares_memory(x1, x4))

False


**hstack vs vstack function**


Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

NumPy provides a helper function: 

1. hstack() to stack along rows.
2. vstack()  to stack along columns

In [53]:
import numpy as np

result = np.hstack((x1, x4))

print(result)

[[100   3 100   3]
 [  5   6   5   6]
 [  8   9   8 900]]


In [54]:
import numpy as np

result = np.vstack((x1, x4))

print(result)

[[100   3]
 [  5   6]
 [  8   9]
 [100   3]
 [  5   6]
 [  8 900]]


We hope now you saw the difference between them.

Fun fact! you can even use concatenate() function to join 2 arrays along with the axis. If axis is not explicitly passed, it is taken as 0 ie. along column

Lets try this function as well

In [55]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.concatenate((arr1, arr2), axis=0)

print(result)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [56]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.concatenate((arr1, arr2), axis=1)

print(result)

[[1 2 5 6]
 [3 4 7 8]]


## Adding, Insert and delete Numpy array

You can also add 2 arrays using append() function also. This function appends values to end of array

Lets see how

In [57]:
import numpy as np

arr1 = np.array([[1, 2],
                 [3, 4]])

arr2 = np.array([[5, 6],
                 [7, 8]])

result = np.append(arr1, arr2)

print(result)

[1 2 3 4 5 6 7 8]


Lets use insert() function which Inserts values into array before specified index value

In [58]:
import numpy as np

result = np.insert(x1, 4, x4)

print(result)

ValueError: could not broadcast input array from shape (3,2) into shape (3,)

You can see in above output we have inserted all the elements of x4 before index 4 in array x1.

In [ ]:
import numpy as np

result = np.delete(x2, 1)

print(result)

Did you see? 2 value is deleted from x2 which was at index position 2

Good Job learner! 